name: 'Pull Request'

on:
  pull_request:
    branches: master

concurrency:
  group: ci-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-lint:
    uses: ./.github/workflows/_webext-lint.yml
