name: Release notifier

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Notify IRC
        uses: Gottox/irc-message-action@v2
        with:
          server: "irc.libera.chat"
          channel: "#shiori"
          nickname: ShioriBot
          tls: true
          sasl_password: ${{ secrets.IRC_SHIORIBOT_PWD }}
          message: "New release: ${{ github.event.repository.full_name }}@${{ github.event.release.name }}: ${{ github.event.release.html_url }}"
