name: 'Tag'

on:
  push:
    tags:
    - v*

jobs:
  get-version:
    steps:
      - name: get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

  call-build:
    uses: ./.github/workflows/_webext-build.yml
    secrets:
      signKey: ${{ secrets.AMO_SIGN_KEY }}
      signSecret: ${{ secrets.AMO_SIGN_SECRET }}

  call-release:
    needs: call-build
    uses: ./.github/workflows/_release.yml
    with:
      tag: ${{ steps.get-version.outputs.VERSION }}
